;; This file was generated by wasmate.py, which is a script that converts
;; from the "flat" text assembly syntax emitted by LLVM into the s-expression
;; syntax expected by the spec repository.
;;
;; Note: this is a hack. A real toolchain will eventually be needed.
;;

(module
  (export "memory_size" $memory_size)
  (func $memory_size
    (result i64)
    (local i64)
    (set_local 0 (memory_size ))
    (return (get_local 0))
  )
  (export "grow_memory" $grow_memory)
  (func $grow_memory
    (param i64)
    (local i64)
    (set_local 1 (get_local 0))
    (grow_memory (get_local 1))
    (return)
  )
  (memory 0 0
    (segment 0
      ""
    )
  )
)
