;; This file was generated by wasmate.py, which is a script that converts
;; from the "flat" text assembly syntax emitted by LLVM into the s-expression
;; syntax expected by the spec repository.
;;
;; Note: this is a hack. A real toolchain will eventually be needed.
;;

(module
  (export "main" $main)
  (func $main
    (result i32)
    (local i32 i32)
    (set_local 0 (i32.const 4))
    (set_local 1 (i32.load (get_local 0)))
    (return (get_local 1))
  )
  (memory 8 8
    (segment 0
      "\04\00\00\00\00\00\00\00"
    )
  )
)
