;; This file was generated by wasmate.py, which is a script that converts
;; from the "flat" text assembly syntax emitted by LLVM into the s-expression
;; syntax expected by the spec repository.
;;
;; Note: this is a hack. A real toolchain will eventually be needed.
;;

(module
  (export "return_void" $return_void)
  (func $return_void
    (return)
  )
  (memory 0 0
    (segment 0
      ""
    )
  )
)
