(module
  (export "sti32" $sti32)
  (func $sti32
    (param i32)
    (param i32)
    (local i32 i32)
    (set_local 2 (get_local 1))
    (set_local 3 (get_local 0))
    (i32.store (get_local 3) (get_local 2))
    (return)
  )
  (export "sti64" $sti64)
  (func $sti64
    (param i32)
    (param i64)
    (local i64 i32)
    (set_local 2 (get_local 1))
    (set_local 3 (get_local 0))
    (i64.store (get_local 3) (get_local 2))
    (return)
  )
  (export "stf32" $stf32)
  (func $stf32
    (param i32)
    (param f32)
    (local f32 i32)
    (set_local 2 (get_local 1))
    (set_local 3 (get_local 0))
    (f32.store (get_local 3) (get_local 2))
    (return)
  )
  (export "stf64" $stf64)
  (func $stf64
    (param i32)
    (param f64)
    (local f64 i32)
    (set_local 2 (get_local 1))
    (set_local 3 (get_local 0))
    (f64.store (get_local 3) (get_local 2))
    (return)
  )
  (memory 0 0
    (segment 0
      ""
    )
  )
)
